db:
  path: "db/database.sqlite3"
  migrations_dir: "db/migrations"

storage:
  base_path: "media"

log_level: "INFO"
api_addr: "127.0.0.1:8000"
cdn_url: "http://127.0.0.1:8000"

whitelisted_pubkeys:
  - "<pubkey_hex>"