// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: mime_types.sql

package db

import (
	"context"
)

const getMimeType = `-- name: GetMimeType :one
SELECT extension, mime_type, allowed
FROM mime_types
WHERE mime_type = ?
LIMIT 1
`

func (q *Queries) GetMimeType(ctx context.Context, mimeType string) (MimeType, error) {
	row := q.db.QueryRowContext(ctx, getMimeType, mimeType)
	var i MimeType
	err := row.Scan(&i.Extension, &i.MimeType, &i.Allowed)
	return i, err
}
