// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type AccessControlRule struct {
	Action   string
	Pubkey   string
	Resource string
}

type Blob struct {
	Pubkey  string
	Hash    string
	Type    string
	Size    int64
	Blob    []byte
	Created int64
}

type MimeType struct {
	Extension string
	MimeType  string
	Allowed   int64
}

type Setting struct {
	Key   string
	Value string
}
